import {lazy,Suspense} from 'react';
const PdfReader=lazy(()=>import('./PdfReader'));
import {useEffect,useRef,useState} from 'react';
import {BookOpenText,CloudArrowUp,ArrowLeft,ArrowRight,LockKey,UploadSimple,X,MagnifyingGlass} from '@phosphor-icons/react';
import {useLocale} from './Locale';
import {createLibraryClient,DEFAULT_REPO} from './private-library';
import {readDevice,rememberDevice,forgetDevice,DEVICE_KEY} from './library-device';
const collection=['毛泽东选集67年版 第一卷 (毛泽东)','毛泽东选集67年版 第二卷 (毛泽东)','毛泽东选集67年版 第三卷 (毛泽东)','毛泽东选集67年版 第四卷 (毛泽东)','毛泽东选集 ','毛泽东文集1-8卷','毛选第1卷（1952年版）','毛选第3卷（1952年版）','mzd 农村调查文集','毛主席语录 ','mzd诗词讲解','mzd 读评五部古典小说','《mzd 年谱(全九卷)》 (中央文献研究室) '].map((title,i)=>({id:`pending-${i}`,title,filename:title+'.pdf',pending:true}));
export default function BookLibrary({children,go}){
 const {lang}=useLocale(),en=lang==='en',t=(zh,english)=>en?english:zh;
 const [tab,setTab]=useState('books'),[books,setBooks]=useState(collection),[client,setClient]=useState(null),[repo,setRepo]=useState(DEFAULT_REPO),[token,setToken]=useState(''),[settings,setSettings]=useState(false),[query,setQuery]=useState(()=>sessionStorage.getItem('zhixu-library-query')||''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[opened,setOpened]=useState(null),[url,setUrl]=useState(''),[note,setNote]=useState({page:1,notes:''}),[version,setVersion]=useState(null),[conflict,setConflict]=useState(null);
 const localFile=useRef(null),modal=useRef(null),fileInput=useRef(null),trigger=useRef(null),requestId=useRef(0);
 const [remember,setRemember]=useState(true),[restoring,setRestoring]=useState(false);
 useEffect(()=>{let active=true;async function restore(){let saved;try{saved=readDevice(localStorage);}catch{if(active)setStatus('无法读取本设备授权，请手动连接。 / Device storage unavailable.');return;}if(!saved)return;if(active){setRestoring(true);setRepo(saved.repo);}try{const c=createLibraryClient(saved.repo,saved.token);await c.verify();const list=await c.list();if(active){setClient(c);setBooks(list);setStatus('已自动连接你的私有书库。 / Private library connected automatically.');}}catch(e){if(active){if(e.status===401){try{forgetDevice(localStorage);}catch{}}setSettings(true);setStatus('自动连接失败，请检查网络或重新授权。 / Reconnect or check your network.');}}finally{if(active)setRestoring(false);}}restore();const changed=e=>{if(e.key!==DEVICE_KEY&&e.key!==null)return;active=false;setClient(null);setToken('');setBooks(collection);setSettings(true);setRestoring(false);++requestId.current;modal.current?.close();setOpened(null);setUrl('');setStatus('设备授权已在其他标签页更改，请重新连接。 / Authorization changed in another tab.');};window.addEventListener('storage',changed);return()=>{active=false;window.removeEventListener('storage',changed);};},[]);
 const disconnect=()=>{++requestId.current;setClient(null);setToken('');setBooks(collection);setOpened(null);setUrl('');modal.current?.close();try{forgetDevice(localStorage);setStatus(t('已退出并忘记本设备授权。已下载的文件和本机笔记不会删除。','Signed out and device authorization removed. Downloads and local notes are retained.'));}catch{setStatus(t('退出成功，但无法清除设备存储。请清除此网站的数据或在 GitHub 撤销令牌。','Signed out, but storage could not be cleared. Clear site data or revoke the token on GitHub.'));}};
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url);},[url]);
 useEffect(()=>{sessionStorage.removeItem('zhixu-library-query');},[]);
 useEffect(()=>{if(opened&&!modal.current?.open)modal.current?.showModal();},[opened]);
 const connect=async e=>{e.preventDefault();if(restoring)return;setBusy(true);setStatus('');try{const c=createLibraryClient(repo,token);await c.verify();const list=await c.list();let stored=true;try{if(remember)rememberDevice(localStorage,repo,token);else forgetDevice(localStorage);}catch{stored=false;}setClient(c);setBooks(list);setToken('');setSettings(false);setStatus(stored?t(remember?'已连接并记住本设备，下次自动打开。':'已连接，仅本次使用。',remember?'Connected. This device will reconnect automatically.':'Connected for this visit only.'):t('已连接，但浏览器无法保存授权；请勿在共享设备继续使用，或清除网站数据后重试。','Connected, but device storage could not be updated. Clear site data before using a shared device.'));}catch(e){setStatus(e.message);}finally{setBusy(false);}};
 const open=async(book,event)=>{if(book.pending){setSettings(true);setStatus(t('先连接私有 GitHub 书库以读取原书。','Connect your private GitHub library to read.'));return;}trigger.current=event.currentTarget;setOpened(book);setUrl('');setStatus('');setVersion(null);setConflict(null);let draft={page:1,notes:''};try{draft=JSON.parse(localStorage.getItem('zhixu-book-'+book.id))||draft;}catch{setStatus(t('本地笔记读取失败，请勿关闭现有草稿。','Could not load the local draft.'));}setNote(draft);const n=++requestId.current;setBusy(true);try{const remote=await client.note(book.id);const blob=await client.download(book);if(n!==requestId.current)return;setVersion(remote.sha);if(!draft.updatedAt)setNote(remote.value);else if(remote.value.updatedAt>draft.updatedAt){setConflict(remote.value);setStatus(t('远端有更新。你的本地草稿已保留；可下载原书并比较笔记。','Remote notes are newer. Your local draft is preserved.'));}setUrl(URL.createObjectURL(blob));}catch(e){setStatus(e.message);}finally{if(n===requestId.current)setBusy(false);}};
 const edit=(next)=>{const value={...note,...next,updatedAt:new Date().toISOString()};setNote(value);try{localStorage.setItem('zhixu-book-'+opened.id,JSON.stringify(value));}catch{setStatus(t('本地保存失败，请复制笔记备份。','Local save failed. Please copy your notes.'));}};
 const close=()=>{if(!window.matchMedia("(prefers-reduced-motion: reduce)").matches){modal.current?.classList.add("is-closing");setTimeout(finishClose,220);}else finishClose();};
 const finishClose=()=>{modal.current?.classList.remove("is-closing");++requestId.current;modal.current?.close();setOpened(null);setUrl('');setBusy(false);trigger.current?.focus();};
 const sync=async()=>{setBusy(true);try{setVersion(await client.saveNote(opened.id,note,version));setStatus(t('阅读页码与精读笔记已同步到私有仓库。','Reading position and notes synced privately.'));}catch(e){setStatus(e.message);}finally{setBusy(false);}};
 const upload=async e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(!client){setSettings(true);return;}setBusy(true);try{for(const file of files){setStatus(t('正在上传：','Uploading: ')+file.name);const book=await client.upload(file);setBooks(current=>[book,...current.filter(b=>b.id!==book.id)]);}setStatus(t('已上传并同步，其他设备连接同一仓库即可看到。','Uploaded. Connect the same repository on another device to read.'));}catch(e){setStatus(e.message);}finally{setBusy(false);}};
 return <section className="book-library">{restoring&&<p className="library-status" role="status">{t("正在验证本设备授权…","Verifying device authorization…")}</p>}<div className="library-heading"><div><p className="study-kicker">YOUR PRIVATE LIBRARY</p><h1>{t('把读过的，变成自己的。','Make knowledge your own.')}</h1><p>{t('一本书，一页思考。慢慢读，真正理解。','One book. One thoughtful page at a time.')}</p></div><button className="glass-control" onClick={()=>setSettings(!settings)}><LockKey size={18}/>{client?t('已连接 · 设置','Connected · Settings'):t('连接私有书库','Connect private library')}</button></div>
 {settings&&<form className="library-connect" onSubmit={connect}><h2>{t('私有 GitHub 同步','Private GitHub sync')}</h2><p>{t('每台设备首次验证后，可记住授权并自动连接。授权保存在本浏览器，同源脚本和使用此设备的人可能访问；不要在共享设备勾选。令牌到期或撤销后需重新验证。','Remember authorization on your own device to reconnect automatically. It is stored in this browser and accessible to same-origin scripts and people using this device. Reauthorize if the token expires or is revoked.')}</p><label>{t('仓库','Repository')}<input value={repo} onChange={e=>setRepo(e.target.value)} autoComplete="off" required/></label><label>{t('细粒度令牌（仅此仓库 Contents 读写权限）','Fine-grained token (Contents read/write for this repository only)')}<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} required/></label><label style={{display:"flex",alignItems:"center",gap:10}}><input style={{width:18}} type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>{t("记住本设备（仅限个人设备）","Remember this personal device")}</label><div><button disabled={busy||restoring} className="glass-control">{busy?t('连接中…','Connecting…'):t('安全连接','Connect')}</button>{client&&<button type="button" className="glass-control" onClick={disconnect}>{t('退出并忘记本设备','Sign out & forget device')}</button>}<a href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noreferrer">{t('在 GitHub 创建令牌','Create a token on GitHub')}</a></div></form>}
 <input hidden ref={localFile} type="file" accept=".pdf,application/pdf" onChange={async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;if(file.size>200*1024*1024){setStatus(t("本地阅读限 200 MB PDF","Local reading supports PDFs up to 200 MB"));return;}const bytes=new Uint8Array(await file.slice(0,5).arrayBuffer());if(new TextDecoder().decode(bytes)!=="%PDF-"){setStatus(t("请选择有效 PDF","Choose a valid PDF"));return;}setOpened({id:"local-"+file.name+file.size,title:file.name,filename:file.name,local:true});try{setNote(JSON.parse(localStorage.getItem("zhixu-book-local-"+file.name+file.size))||{page:1,notes:""});}catch{setNote({page:1,notes:""});}setConflict(null);setUrl(URL.createObjectURL(file));setStatus(t("本地试读，尚未上传或同步。","Local preview only; not uploaded or synced."));}}/><div className="library-tools">{client&&<button className="glass-control" disabled={busy} onClick={async()=>{setBusy(true);try{setBooks(await client.list());setStatus(t("书架已刷新","Bookshelf refreshed"));}catch(e){setStatus(e.message);}finally{setBusy(false);}}}>{t("刷新书架","Refresh shelf")}</button>}<div className="library-tabs"><button aria-pressed={tab==='books'} onClick={()=>setTab('books')}>{t('书架','Bookshelf')}</button><button aria-pressed={tab==='notes'} onClick={()=>setTab('notes')}>{t('知识文件','Knowledge files')}</button></div>{tab==='books'&&<><label className="shelf-search"><MagnifyingGlass size={19}/><input aria-label={t('搜索书籍','Search books')} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('搜索书名','Search titles')}/></label><button className="glass-control" disabled={busy} onClick={()=>client?fileInput.current.click():setSettings(true)}><UploadSimple size={18}/>{t('上传书籍','Upload books')}</button><button className="glass-control" onClick={()=>localFile.current.click()}>{t("本地试读","Read local PDF")}</button><input ref={fileInput} type="file" accept="application/pdf,.pdf" multiple hidden onChange={upload}/></>}</div>
 {status&&<p className="library-status" role="status">{status}</p>}
 {tab==='notes'?children:<><p className="library-caption">{client?t(`${books.length} 本原书 · 私有存储`,'Original PDFs · Private storage'):t('13 本个人收藏 · 连接后读取原书，封面为书名排版，非原版封面','13 collected titles · Connect to read original PDFs; typographic covers are not original editions')}</p><div className="book-shelf">{books.filter(b=>b.title.toLowerCase().includes(query.toLowerCase())).map((book,i)=><button className={`shelf-book book-tone-${i%4}`} key={book.id} onClick={e=>open(book,e)}><div className="book-cover"><span>知序 · 藏书</span><BookOpenText size={24}/><strong>{book.title}</strong><small>{book.pending?t('连接后阅读','Connect to read'):t('打开原书','Open PDF')}</small></div><span className="book-caption">{book.title}</span></button>)}</div>{!books.filter(b=>b.title.toLowerCase().includes(query.toLowerCase())).length&&<p className="library-status">{t('没有匹配的书籍。试试其他书名，或上传一本。','No matching books. Try another title or upload a PDF.')}</p>}<button className="glass-control" onClick={()=>go('mao')}>{t('毛选研读：问题、理解与行动','Mao studies: questions, understanding and action')}<ArrowRight size={18}/></button></>}
 <dialog className="book-reader" ref={modal} onCancel={e=>{e.preventDefault();close();}}>{opened&&<><header><div><small>{t('正在精读','CLOSE READING')}</small><h2>{opened.title}</h2></div><button className="glass-control" onClick={close}><X size={20}/>{t('合上并放回','Return to shelf')}</button></header><div className="reader-spread"><section className="pdf-pane">{url?<><Suspense fallback={<p>{t("准备阅读器…","Preparing reader…")}</p>}><PdfReader url={url} page={note.page} onPage={page=>edit({page})} en={en}/></Suspense><a href={url} download={opened.filename}>{t('下载原书 / 手机无法预览时打开','Download PDF / Open if preview is unavailable')}</a></>:<p role="status">{busy?t('正在从私有书库取书…大扫描版首次加载较慢。','Fetching your book… Large scans take longer.'):t('读取未完成，请合上后重试。','Could not open this book. Close and try again.')}</p>}</section><aside className="book-journal"><h3>{t('今天，只读懂几页。','A few pages. A deeper understanding.')}</h3><p>{t('每次建议 3–5 页，约 20 分钟。不求读快，先看清作者的问题、证据与条件。','Read 3–5 pages in about 20 minutes. Identify the question, evidence and conditions.')}</p><label>{t('下次继续的 PDF 页码（与纸书页码可能不同）','PDF page to resume (may differ from printed page)')}<input type="number" min="1" max="10000" value={note.page} onChange={e=>edit({page:Math.max(1,Math.min(10000,Number(e.target.value)||1))})}/></label><ol><li>{t('预读 2 分钟：这几页在回答什么问题？','Preview: What question do these pages answer?')}</li><li>{t('精读 10 分钟：找出结论、论据、适用条件。遇到陌生背景先标记，不急着类比。','Read: identify claims, evidence and conditions; flag unfamiliar context.')}</li><li>{t('合书 5 分钟：用自己的话解释，并举一个反例。','Recall: explain in your own words and give a counterexample.')}</li><li>{t('实践 3 分钟：制定一个可验证的小行动，明天复盘。','Apply: choose one testable action and review tomorrow.')}</li></ol><label>{t('精读笔记 · 自动保存在本设备','Reading notes · Saved on this device')}<textarea value={note.notes||''} onChange={e=>edit({notes:e.target.value})} maxLength={30000} placeholder={t('页码 / 篇名：\n作者的问题：\n核心观点与证据：\n历史背景与适用边界：\n我的解释 / 反例：\n明天的行动与检验：','Pages / article:\nQuestion:\nClaim and evidence:\nContext and limits:\nMy explanation / counterexample:\nAction and test:')}/></label><div>{conflict&&<><p>{t("远端有更新，请先选择：","Newer remote notes. Choose a version first:")}</p><button className="glass-control" onClick={()=>{edit(conflict);setConflict(null);}}>{t("使用远端版本","Use remote version")}</button><button className="glass-control" onClick={()=>setConflict(null)}>{t("保留本地版本并允许同步","Keep local and allow sync")}</button></>}</div><button className="glass-control" disabled={busy||!url||!client||opened.local||!!conflict} onClick={sync}><CloudArrowUp size={20}/>{t('同步页码与笔记','Sync page & notes')}</button><p className="library-status" role="status">{status}</p><small>{t('这是精读方法引导，不是对未解析原文的 AI 分析。原书仅在你连接后加载。','This is a reading method, not AI analysis of unparsed text. PDFs load only after connecting.')}</small></aside></div></>}</dialog>
 </section>;
}
