export const growthDomains = [
  {
    id: "professional",
    label: "专业能力",
    note: "沉淀一条可复用方法",
    progress: 68,
    color: "violet",
    icon: "Code",
  },
  {
    id: "ai",
    label: "AI 与自动化",
    note: "完成个人作品检索模块",
    progress: 60,
    color: "mint",
    icon: "Robot",
  },
  {
    id: "english",
    label: "英语表达",
    note: "专业表达训练 30 分钟",
    progress: 75,
    color: "blue",
    icon: "ChatCircle",
  },
  {
    id: "output",
    label: "知识输出",
    note: "精读输出：有效管理者",
    progress: 65,
    color: "amber",
    icon: "BookOpenText",
  },
  {
    id: "wellbeing",
    label: "健康与生活",
    note: "本周运动 3 / 4",
    progress: 75,
    color: "green",
    icon: "Heart",
  },
];

export const seedKnowledge = [
  {
    id: "vector-db",
    title: "向量数据库实践",
    type: "文档",
    fileType: "md",
    space: "AI 与自动化",
    size: "18 KB",
    updatedAt: "2026-08-18T21:10:00.000Z",
    status: "ready",
    tags: ["检索", "AI 作品"],
    summary: "从数据分块、向量化、相似度召回到引用回链的完整实践笔记。",
    content:
      "检索模块应先完成数据分块与元数据设计，再实现向量化、相似度召回和结果重排。每条结果必须保存来源、章节和片段，回答时回链原文。第一版优先保证可验证性，再优化召回质量。",
    source: "第 3 章 · 向量检索实现",
    favorite: true,
  },
  {
    id: "weekly-review",
    title: "本周成长复盘",
    type: "笔记",
    fileType: "md",
    space: "成长战略",
    size: "12 KB",
    updatedAt: "2026-08-16T13:30:00.000Z",
    status: "ready",
    tags: ["复盘", "关键行动"],
    summary: "检索模块原型已验证，下一步应收敛范围并形成可展示的作品证据。",
    content:
      "本周已完成知识卡片与检索原型。当前最大问题不是功能不足，而是范围过大。下周只推进一件事：完成检索模块、补齐引用回链和三个关键测试，并记录设计取舍。",
    source: "周复盘 · 关键行动",
    favorite: false,
  },
  {
    id: "skill-roadmap",
    title: "年度技能路线",
    type: "路线图",
    fileType: "md",
    space: "AI 与自动化",
    size: "26 KB",
    updatedAt: "2026-08-14T08:40:00.000Z",
    status: "ready",
    tags: ["年度技能", "作品"],
    summary: "AI 应用落地路线：从原型到可复用模块，再形成公开作品与方法论。",
    content:
      "第三季度重点是把 AI 编程从学习活动转化为作品。核心交付包括：可复用的知识检索模块、带来源引用的问答界面、结构化上传流程和一篇完整的实现复盘。",
    source: "路线图 · Q3 重点任务",
    favorite: true,
  },
  {
    id: "effective-executive",
    title: "《卓有成效的管理者》精读",
    type: "读书笔记",
    fileType: "md",
    space: "阅读与写作",
    size: "34 KB",
    updatedAt: "2026-08-12T20:15:00.000Z",
    status: "ready",
    tags: ["精读", "输出"],
    summary: "用时间记录、贡献意识和要事优先改善个人执行系统。",
    content:
      "有效不是完成更多任务，而是集中时间做真正重要的贡献。先记录时间，再找出可以整块投入的时间。每周只确定一件必须推进的要事，并明确它如何形成成果。",
    source: "第 2 章 · 掌握自己的时间",
    favorite: false,
  },
  {
    id: "english-expression",
    title: "专业会议表达卡",
    type: "学习卡",
    fileType: "txt",
    space: "英语",
    size: "8 KB",
    updatedAt: "2026-08-11T07:20:00.000Z",
    status: "ready",
    tags: ["英语", "表达"],
    summary: "用 Situation–Risk–Action 结构进行清晰的专业进展汇报。",
    content:
      "A concise professional update uses three moves: state the situation, name the most important risk, and ask for or commit to one action. Keep the main point in the first two sentences and finish with an owner and timing.",
    source: "表达卡 · Situation–Risk–Action",
    favorite: false,
  },
  {
    id: "strength-plan",
    title: "力量训练与恢复计划",
    type: "计划",
    fileType: "md",
    space: "健康与生活",
    size: "10 KB",
    updatedAt: "2026-08-10T18:00:00.000Z",
    status: "ready",
    tags: ["运动", "恢复"],
    summary: "每周四次短训练，以稳定睡眠和渐进负荷为优先。",
    content:
      "本周安排四次 45 分钟训练。强度以动作稳定为前提，不追求力竭。晚间训练后留出一小时降温与放松时间，优先保证连续睡眠。",
    source: "第 34 周训练安排",
    favorite: false,
  },
  {
    id: "hygiene-method",
    title: "卫生风险登记方法",
    type: "专业方法",
    fileType: "pdf",
    space: "工作知识",
    size: "1.6 MB",
    updatedAt: "2026-08-08T09:15:00.000Z",
    status: "ready",
    tags: ["工作", "方法论"],
    summary: "把风险转化为可验证需求、责任人和关闭证据。",
    content:
      "风险登记应包含风险描述、影响、控制措施、验证方式、负责人和关闭证据。它是工作知识中的一个普通方法条目，不代表个人成长系统的核心目标。",
    source: "工作知识 · 方法论",
    favorite: false,
  },
];

export const seedActions = [
  {
    id: "action-search-module",
    title: "完成个人 AI 编程作品的检索模块",
    detail: "实现关键词与向量召回接口，补齐引用回链和三个关键测试。",
    domain: "AI 与自动化",
    duration: "90 分钟",
    evidence: "检索模块实现文档",
    completed: false,
  },
  {
    id: "action-english",
    title: "英语专业表达训练",
    detail: "用 Situation–Risk–Action 结构完成一次 3 分钟录音。",
    domain: "英语表达",
    duration: "30 分钟",
    evidence: "训练录音与表达卡",
    completed: false,
  },
  {
    id: "action-reading",
    title: "完成一张精读输出卡",
    detail: "把“要事优先”转化为明天的时间块安排。",
    domain: "知识输出",
    duration: "25 分钟",
    evidence: "精读输出卡",
    completed: false,
  },
];

export const spaces = [
  "全部知识",
  "收件箱",
  "AI 与自动化",
  "英语",
  "阅读与写作",
  "专业能力",
  "健康与生活",
  "工作知识",
  "成长战略",
];
