import {useEffect,useRef,useState} from 'react';
import {BookOpenText,LockKey,X,MagnifyingGlass,ArrowRight} from '@phosphor-icons/react';
import {useLocale} from './Locale';
import {unlockBook,decryptBook} from './book-crypto';
import ReadingWorkspace from './ReadingWorkspace';
import {normalizeNote,exportReading} from './reading-annotations';
const base=import.meta.env.BASE_URL+'encrypted-books/';
export default function EncryptedLibrary({children,go}){
 const {lang}=useLocale(),en=lang==='en',t=(a,b)=>en?b:a;
 const [books,setBooks]=useState([]),[query,setQuery]=useState(()=>{try{return sessionStorage.getItem('zhixu-library-query')||'';}catch{return '';}}),[tab,setTab]=useState('books'),[status,setStatus]=useState(''),[selected,setSelected]=useState(null),[url,setUrl]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[note,setNote]=useState({page:1,notes:''}),[journal,setJournal]=useState(false);
 const dialog=useRef(null),cancel=useRef(null),generation=useRef(0),local=useRef(null),trigger=useRef(null);
 const refresh=async()=>{setStatus(t('正在读取书架…','Loading bookshelf…'));try{const r=await fetch(base+'catalog.json',{cache:'no-cache'});if(!r.ok)throw Error();const c=await r.json();if(c.version!==1||!Array.isArray(c.books))throw Error();setBooks(c.books);setStatus('');}catch{setStatus(t('加密书库尚未发布或网络不可用。请稍后刷新；也可直接阅读本机 PDF。','Encrypted collection not yet published or unavailable. Retry, or read a local PDF.'));}};
 useEffect(()=>{refresh();try{sessionStorage.removeItem('zhixu-library-query');}catch{}return()=>{++generation.current;cancel.current?.abort();};},[]);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url);},[url]);
 useEffect(()=>{if(selected&&!dialog.current.open)dialog.current.showModal();},[selected]);
 const close=()=>{++generation.current;cancel.current?.abort();setPassword('');setUrl('');setSelected(null);setBusy(false);setStatus('');dialog.current?.close();trigger.current?.focus();};
 useEffect(()=>{if(!url)return;let timer;const reset=()=>{clearTimeout(timer);timer=setTimeout(close,5*60*1000);};reset();const events=['pointerdown','keydown','scroll'];events.forEach(e=>window.addEventListener(e,reset,true));window.addEventListener('pagehide',close);return()=>{clearTimeout(timer);events.forEach(e=>window.removeEventListener(e,reset,true));window.removeEventListener('pagehide',close);};},[url]);
 const loadNote=book=>{let value={page:1,notes:''};try{value=JSON.parse(localStorage.getItem('zhixu-book-'+book.id)||localStorage.getItem('zhixu-book-'+book.legacyId)||'null')||value;}catch{}setNote(normalizeNote(value));};
 const choose=(book,event)=>{trigger.current=event.currentTarget;setSelected(book);setPassword('');setStatus('');setUrl('');setJournal(false);loadNote(book);};
 const unlock=async e=>{e.preventDefault();const secret=password;setPassword('');setBusy(true);setStatus(t('正在验证口令…','Checking passphrase…'));const n=++generation.current;const controller=new AbortController();cancel.current=controller;let key;
  try{key=await unlockBook(selected,secret);}catch{if(n===generation.current){setBusy(false);setStatus(t('口令不正确，或加密目录已损坏。请重试。','Incorrect passphrase or damaged catalog. Try again.'));}return;}
  if(n!==generation.current)return;
  try{const blob=await decryptBook(selected,key,base,controller.signal,(a,b)=>{if(n===generation.current)setStatus(t(`下载并解密 ${a} / ${b} 段，请保持页面打开。`,`Downloading and decrypting ${a} / ${b} chunks.`));});if(n!==generation.current)return;setUrl(URL.createObjectURL(blob));setStatus('');}catch(e){if(n===generation.current)setStatus(t('读取失败：网络中断或文件损坏，请重新解锁。','Read failed: network interruption or damaged file. Unlock again.'));}finally{key=null;if(n===generation.current)setBusy(false);}
 };
 const edit=next=>{const v={...note,...next,updatedAt:new Date().toISOString()};setNote(v);try{localStorage.setItem('zhixu-book-'+selected.id,JSON.stringify(v));}catch{setStatus(t('笔记保存失败，请复制备份。','Could not save notes. Copy a backup.'));}};
 const exportNote=()=>{const blob=new Blob([exportReading(selected.title,note)],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=selected.title+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
 const readLocal=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>300*1024*1024||new TextDecoder().decode(await file.slice(0,5).arrayBuffer())!=='%PDF-'){setStatus(t('请选择 300 MB 以内的有效 PDF。','Choose a valid PDF below 300 MB.'));return;}const book={id:'local-'+file.name+file.size,title:file.name,filename:file.name,local:true};setSelected(book);setJournal(false);loadNote(book);setUrl(URL.createObjectURL(file));setStatus('');};
 return <section className="book-library"><div className="library-heading"><div><p className="study-kicker">YOUR ENCRYPTED LIBRARY</p><h1>{t('一本书，一段自己的时光。','A book. A moment for yourself.')}</h1><p>{t('点击书籍，输入口令，在本设备解密阅读。无需 GitHub 令牌。','Choose a book and unlock it on this device. No GitHub token.')}</p></div><button className="glass-control" onClick={refresh}>{t('刷新书架','Refresh')}</button></div>
 <div className="library-tools"><div className="library-tabs"><button aria-pressed={tab==='books'} onClick={()=>setTab('books')}>{t('书架','Bookshelf')}</button><button aria-pressed={tab==='files'} onClick={()=>setTab('files')}>{t('知识文件','Knowledge files')}</button></div><label className="shelf-search"><MagnifyingGlass size={20}/><input aria-label={t('搜索书名','Search titles')} placeholder={t('搜索书名','Search titles')} value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="glass-control" onClick={()=>local.current.click()}>{t('导入本机 PDF 阅读','Read local PDF')}</button><input hidden ref={local} type="file" accept="application/pdf,.pdf" onChange={readLocal}/></div>
 {!selected&&status&&<p role="status" className="library-status">{status}</p>}
 {tab==='files'?children:<><p className="library-caption">{t(`${books.length} 本加密原书 · 书名公开，正文加密 · 不活动 5 分钟自动锁定` ,`${books.length} encrypted books · Titles public, contents encrypted · Locks after 5 minutes of inactivity`)}</p><div className="book-shelf">{books.filter(b=>b.title.toLowerCase().includes(query.toLowerCase())).map((b,i)=><button key={b.id} className={`shelf-book book-tone-${i%4}`} onClick={e=>choose(b,e)}><div className="book-cover"><span>知序 · 藏书</span><BookOpenText size={26}/><strong>{b.title}</strong><small><LockKey size={14}/>{t('口令解锁','Unlock to read')}</small></div><span className="book-caption">{b.title}</span></button>)}</div><button className="glass-control" onClick={()=>go('mao')}>{t('进入毛选研读','Study guides')}<ArrowRight size={18}/></button></>}
 <dialog ref={dialog} className={`encrypted-reader ${url?'is-reading':''}`} onCancel={e=>{e.preventDefault();close();}}>{selected&&<><header><h2>{selected.title}</h2><button aria-label={t('锁定并合上','Lock and close')} onClick={close}><X size={22}/></button></header>{!url?<form className="book-unlock" onSubmit={unlock}><LockKey size={38}/><h3>{t('解锁这本书','Unlock this book')}</h3><p>{t('口令仅用于本机解密，不上传、不保存。首次打开大扫描版需要下载完整文件。','Passphrase stays on this device and is not saved. Large scans must download before reading.')}</p><label>{t('书库长口令','Library passphrase')}<input autoFocus type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)} disabled={busy} required/></label><button disabled={busy} type="submit">{busy?t('正在解锁…','Unlocking…'):t('解锁阅读','Unlock & read')}</button>{status&&<p role="status">{status}</p>}</form>:<><div className="reader-toolbar"><button aria-pressed={!journal} onClick={()=>setJournal(false)}>{t('阅读','Read')}</button><button aria-pressed={journal} onClick={()=>setJournal(true)}>{t('精读笔记','Notes')}</button><a href={url} download={selected.filename}>{t('下载已解锁原书','Download unlocked PDF')}</a></div><div className="encrypted-reading-body"><ReadingWorkspace url={url} note={note} edit={edit} en={en} journal={journal} setJournal={setJournal} status={status}/><button className="reader-export" onClick={exportNote}>{t('导出笔记与标注','Export notes & marks')}</button></div></>}</>}</dialog>
 </section>;
}
