import {Localize,LanguageSwitch} from './Locale';
import { useEffect, useRef, useState } from 'react';
import MaoStudy from './MaoStudy';

import StudyHome from './StudyHome';
import BookLibrary from './EncryptedLibrary';
import './orbit-v12.css';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowRight, ArrowUpRight, BookOpenText, Books, Check, CheckCircle, Clock, DownloadSimple, Headphones, House, MagnifyingGlass, Microphone, NotePencil, Plus, Sparkle, Target, TrendUp, SpeakerHigh, ArrowLeft, X } from '@phosphor-icons/react';
import { readings, talks, words, wordReferences, bookReferences, dailyReading, dailyTalk, localDay, dueDate } from './learning-content.js';

const nav = [['dashboard', '今日学习', House], ['english', '英语学习', Headphones], ['reading', '每日精读', BookOpenText], ['vocabulary', '词汇复习', Books], ['expression', '表达训练', Microphone], ['notes', '学习笔记', NotePencil], ['library', '知识库', Books], ['ai', '知识问答', Sparkle], ['goals', '我的行动', Target], ['review', '成长回顾', TrendUp]];
nav.push(['mao', '毛选研读', BookOpenText]);
nav.push(['explore', '学习探索', Sparkle]);
const empty = { notes: {}, words: {}, events: [], lastReading: null, lastTalk: null, weeklyReflection: '' };
function useLearning() {
  const [initial] = useState(() => {try {const raw = localStorage.getItem('zhixu-learning-v11');if (!raw) return { data: empty };const value = JSON.parse(raw);if (!value || !value.notes || !value.words || !Array.isArray(value.events)) throw Error();return { data: { ...empty, ...value } };} catch {return { data: empty, error: '学习记录暂时无法读取，本次编辑可导出备份，原记录不会被覆盖。' };}});
  const [data, setData] = useState(initial.data),[error, setError] = useState(initial.error || '');
  useEffect(() => {if (initial.error) return;try {localStorage.setItem('zhixu-learning-v11', JSON.stringify(data));setError('');} catch {setError('保存失败，请导出笔记备份后再离开页面。');}}, [data, initial.error]);
  return [data, setData, error];
}
function Panel({ children, className = '' }) {return <Localize><section className={`studio-panel ${className}`}>{children}</section></Localize>;}
function Button({ children, onClick, secondary = false, ...props }) {return <Localize><button className={secondary ? 'studio-button secondary' : 'studio-button'} onClick={onClick} {...props}>{children}</button></Localize>;}
function OutLink({ href, children }) {return <Localize><a className="studio-link" href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={16} /></a></Localize>;}

export function LearningStudio({ page, setPage, children, knowledge, setKnowledge, actions, setActions, openUpload }) {
  const reduced = useReducedMotion();const [data, setData, error] = useLearning();const [query, setQuery] = useState('');const [notice, setNotice] = useState('');const [today, setToday] = useState(localDay());const search = useRef(null);
  const [readingId, setReadingId] = useState(data.lastReading || dailyReading().id);const [talkId, setTalkId] = useState(data.lastTalk || dailyTalk().id);const [voiceEvents, setVoiceEvents] = useState([]);
  useEffect(() => {try {const voice = JSON.parse(localStorage.getItem('zhixu-expression-v1') || 'null');const events = Object.entries(voice?.tracks || {}).flatMap(([language, track]) => Object.entries(track.records || {}).filter(([, note]) => note.completedAt).map(([day, note]) => ({ id: `voice-${language}-${day}`, date: localDay(new Date(note.completedAt)), title: `${language === 'zh' ? '中文' : '英文'}表达训练 · Day ${day}`, type: 'voice' })));setVoiceEvents(events);} catch {setVoiceEvents([]);}}, [page]);
  const displayData = { ...data, events: [...data.events, ...voiceEvents] };
  useEffect(() => {const key = (e) => {if ((e.metaKey || e.ctrlKey) && e.key === 'k') {e.preventDefault();search.current?.focus();}if (e.key === 'Escape') setQuery('');};const tick = () => setToday(localDay());window.addEventListener('keydown', key);window.addEventListener('focus', tick);const timer = setInterval(tick, 60000);return () => {window.removeEventListener('keydown', key);window.removeEventListener('focus', tick);clearInterval(timer);};}, []);
  useEffect(() => {if (!notice) return;const timer = setTimeout(() => setNotice(''), 4500);return () => clearTimeout(timer);}, [notice]);
  useEffect(() => {window.scrollTo({ top: 0, behavior: 'instant' });}, [page]);
  useEffect(() => {const restore = () => {const target = location.hash.slice(1);if (nav.some((item) => item[0] === target)) setPage(target);};restore();window.addEventListener('hashchange', restore);return () => window.removeEventListener('hashchange', restore);}, [setPage]);
  const go = (target) => {setQuery('');setPage(target);if (location.hash !== `#${target}`) location.hash = target;};
  const openReading = (id) => {setReadingId(id);setData((current) => ({ ...current, lastReading: id }));go('reading');window.scrollTo({ top: 0, behavior: 'instant' });};
  const openTalk = (id) => {setTalkId(id);setData((current) => ({ ...current, lastTalk: id }));go('english');window.scrollTo({ top: 0, behavior: 'instant' });};
  const updateNote = (id, changes) => setData((current) => {const note = { ...current.notes[id], ...changes, updatedAt: new Date().toISOString() };if (!note.insight?.trim() || !note.action?.trim()) delete note.completedAt;return { ...current, notes: { ...current.notes, [id]: note } };});
  const complete = (id, title, type) => {const note = data.notes[id];if (!note?.insight?.trim() || !note?.action?.trim()) {setNotice('先写下你的理解和下一步行动，再完成这次学习。');return;}const event = { id: `${today}:${id}`, date: today, title, type };setData((current) => ({ ...current, notes: { ...current.notes, [id]: { ...current.notes[id], completedAt: new Date().toISOString() } }, events: [...current.events.filter((item) => item.id !== event.id), event] }));setNotice('已完成，今天的成长又多了一点证据。');};
  const saveKnowledge = (id, title) => {const note = data.notes[id];if (!note?.insight?.trim()) {setNotice('先写一点自己的理解，再存入知识库。');return;}const item = { id: `learning-${id}`, title: `学习笔记 · ${title}`, type: '学习笔记', fileType: 'md', space: '阅读与写作', size: '1 KB', updatedAt: new Date().toISOString(), status: 'ready', tags: ['学习笔记', '个人成长'], summary: note.insight.slice(0, 100), content: `我的理解：${note.insight}\n行动：${note.action || ''}`, source: '学习工作台 · 我的笔记', favorite: false };setKnowledge((current) => [item, ...current.filter((entry) => entry.id !== item.id)]);setNotice('已存入知识库，可以继续检索与整理。');};
  const exportNotes = () => {const text = ['# 知序 · 学习笔记', `导出日期：${today}`, ...Object.entries(data.notes).map(([id, note]) => {const entry = [...readings, ...talks].find((item) => item.id === id);return `## ${entry?.title || id}\n\n我的理解：${note.insight || ''}\n\n下一步：${note.action || ''}\n\n${note.completedAt ? '已完成' : '草稿'}`;}), `## 成长复盘\n${data.weeklyReflection || ''}`].join('\n\n');const url = URL.createObjectURL(new Blob([text], { type: 'text/markdown;charset=utf-8' }));const a = document.createElement('a');a.href = url;a.download = `知序学习笔记-${today}.md`;a.click();setTimeout(() => URL.revokeObjectURL(url), 1000);setNotice('笔记已导出为 Markdown。');};
  const results = query.trim() ? [...nav.map(([id, title]) => ({ id, title, type: '模块', run: () => go(id) })), ...readings.map((item) => ({ ...item, type: '精读', run: () => openReading(item.id) })), ...talks.map((item) => ({ ...item, type: '演讲', run: () => openTalk(item.id) })), ...words.map((item) => ({ ...item, title: `${item.word} · ${item.meaning}`, type: '词汇', run: () => go('vocabulary') }))].filter((item) => `${item.title} ${item.cn || ''}`.toLowerCase().includes(query.trim().toLowerCase())).slice(0, 8) : [];
  const title = nav.find((item) => item[0] === page)?.[1] || '成长战略';
  const noteProps = { data, updateNote, complete, saveKnowledge };
  return <Localize><div className={`studio-layout studio-v14 ${page === "dashboard" ? "is-study-home" : ""}`}>
  <aside className="studio-sidebar"><button className="studio-brand" onClick={() => go('dashboard')}><img src={`${import.meta.env.BASE_URL}knowledge-hub-mark.png`} alt="" /><span>知序<span>KNOWLEDGE, INTO LIFE.</span></span></button><span className="nav-caption">我的成长空间</span><nav aria-label="主导航">{["dashboard","library","notes","explore","ai"].map(key=>nav.find(([id])=>id===key)).map(([id, label, Icon]) => <button key={id} className={page === id ? 'selected' : ''} aria-current={page === id ? 'page' : undefined} onClick={() => go(id)}>{page === id && <motion.span className="studio-nav-lens" layoutId="studio-navigation" transition={{ type: 'spring', bounce: 0, duration: reduced ? 0 : .3 }} />}<Icon size={20} /><span>{label}</span>{id === 'dashboard' && <span className="nav-dot" />}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-caption"><span className="status-dot" /> 每一点积累，都属于你</div><button onClick={() => go('review')} className="studio-profile"><span>W</span><div>Wesley<small>保持好奇，持续生长</small></div><ArrowUpRight size={17} /></button></div></aside>
  <main className="studio-main"><header className="studio-topbar"><div className="studio-breadcrumb">我的空间 <span>/</span> <strong>{title}</strong></div><div className="studio-search"><MagnifyingGlass size={18} /><input ref={search} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索内容、课程与模块" aria-label="搜索内容、课程与模块" /><kbd>⌘ K</kbd>{query && <button aria-label="清空搜索" onClick={() => setQuery('')}><X size={16} /></button>}{query && <div className="studio-search-results">{results.length ? results.map((item) => <button key={`${item.type}-${item.id}`} onClick={item.run}><span>{item.type}</span>{item.title}<ArrowRight size={15} /></button>) : <p>没有找到，试试“专注”“演讲”或“habit”。</p>}</div>}</div><LanguageSwitch /><button className="studio-capture" aria-label="导入知识" onClick={openUpload}><Plus size={18} /><span>导入知识</span></button></header>
   {error && <div className="studio-error" role="alert">{error}<button onClick={exportNotes}>导出备份</button></div>}
   <motion.div key={page} className="studio-page" initial={{ opacity: 0, y: reduced ? 0 : 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduced ? 0 : .22 }}>
    {page === 'dashboard' ? <StudyHome go={go} /> : page === "library" ? <BookLibrary go={go}>{children}</BookLibrary> : page === "explore" ? <><div className="explore-links">{nav.filter(([id])=>["english","reading","vocabulary","expression","goals","mao"].includes(id)).map(([id,label,Icon])=><button className="glass-control" key={id} onClick={()=>go(id)}><Icon size={20}/>{label}</button>)}</div><Today data={displayData} today={today} openReading={openReading} openTalk={openTalk} go={go}/></> : page === 'mao' ? <MaoStudy setKnowledge={setKnowledge} /> : page === 'reading' ? <ReadingPage {...noteProps} id={readingId} setId={openReading} /> : page === 'english' ? <EnglishPage {...noteProps} id={talkId} setId={openTalk} go={go} /> : page === 'vocabulary' ? <Vocabulary data={data} setData={setData} today={today} notify={setNotice} /> : page === 'notes' ? <Notes data={data} openReading={openReading} openTalk={openTalk} exportNotes={exportNotes} saveKnowledge={saveKnowledge} /> : page === 'review' ? <ProgressPage data={displayData} setData={setData} today={today} /> : page === 'goals' ? <ActionPage actions={actions} setActions={setActions} /> : children}
   </motion.div><footer className="studio-footer">知序 · 让学习发生，让成长留下来。<span>笔记保存在当前浏览器 · 请定期导出</span></footer>
  </main><nav className="studio-mobile" aria-label="移动导航">{[nav[0], nav[6], nav[11], nav[5], nav[9]].map(([id, label, Icon]) => <button key={id} aria-current={page === id ? 'page' : undefined} onClick={() => go(id)}><Icon size={20} /><span>{label}</span></button>)}</nav>{notice && <div className="studio-toast" role="status"><CheckCircle size={19} />{notice}<button onClick={() => setNotice('')} aria-label="关闭提示"><X size={16} /></button></div>}
 </div></Localize>;
}

function Today({ data, today, openReading, openTalk, go }) {
  const reading = readings.find((item) => item.id === data.lastReading && !data.notes[item.id]?.completedAt) || dailyReading(),talk = dailyTalk();const completed = data.events.filter((event) => event.date === today);const recent = Object.entries(data.notes).filter(([, note]) => note.insight).sort((a, b) => (b[1].updatedAt || '').localeCompare(a[1].updatedAt || '')).slice(0, 3);
  const due = words.filter((word) => data.words[word.id] && data.words[word.id].due <= today).length;const hour = new Date().getHours();
  return <Localize><><div className="studio-greeting"><div><span className="studio-eyebrow">{new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', weekday: 'long' }).format(new Date())} · A LITTLE BETTER, EVERY DAY</span><h1>{hour < 12 ? '早上好' : hour < 18 ? '下午好' : '晚上好'}，Wesley<span>今天，向喜欢的自己靠近一点。</span></h1><p>读一点，听一点，再用自己的话说出来。</p></div><div className="today-completion"><span className="completion-circle" style={{ '--progress': `${Math.min(completed.length / 3, 1) * 360}deg` }}><strong>{completed.length}</strong></span><span>今日已完成<small>建议节奏 · 3 个小练习</small></span></div></div>
  <div className="today-grid"><Panel className="featured-reading"><div className="feature-copy"><span className="studio-tag"><BookOpenText size={15} /> 今日精读 · {reading.minutes} 分钟</span><h2>{reading.title}</h2><p>{reading.intro}</p><div className="feature-meta"><span>原创成长短文</span><span>阅读 → 思考 → 行动</span></div><Button onClick={() => openReading(reading.id)}>{data.notes[reading.id]?.insight ? '继续精读' : '开始今天的精读'}<ArrowRight size={18} /></Button></div><div className={`editorial-book ${reading.color}`} aria-hidden="true"><span>知序阅读</span><strong>{reading.label}<br />YOUR<br />MIND.</strong><small>一段阅读，一点改变<br />THE DAILY READER · {reading.issue}</small><i /></div><div className="feature-bottom"><span className="status-dot" />{data.notes[reading.id]?.completedAt ? '已经留下了你的理解，随时回来重读。' : '不止于读完，更要留下自己的答案。'}</div></Panel>
  <Panel className="daily-english"><span className="studio-tag"><Headphones size={15} /> 今日英语 · {talk.minutes} 分钟</span><div className={`talk-art ${talk.color}`}><span>LISTEN.<br />THINK.<br /><em>SPEAK.</em></span><button aria-label={`学习演讲 ${talk.title}`} onClick={() => openTalk(talk.id)}><ArrowUpRight size={27} /></button></div><span className="studio-eyebrow">{talk.speaker} · {talk.level}</span><h3>{talk.cn}</h3><p>{talk.title}</p><button className="text-action" onClick={() => openTalk(talk.id)}>进入听说练习<ArrowRight size={17} /></button></Panel>
  <Panel className="daily-plan"><div className="studio-section-head"><h2>你的今日节奏</h2><span>小步，也算数</span></div>{[[BookOpenText, '读一篇，留一个观点', `${reading.minutes} 分钟 · 精读与思考`, () => openReading(reading.id), !!data.notes[reading.id]?.completedAt], [Headphones, '听一段，说三句话', `${talk.minutes} 分钟 · 英语输入与输出`, () => openTalk(talk.id), !!data.notes[talk.id]?.completedAt], [Microphone, '练一次，更清楚一点', '10 分钟 · 中文 / English', () => go('expression'), completed.some((event) => event.type === 'voice')]].map(([Icon, title, detail, run, done]) => <button className="plan-row" key={title} onClick={run}><span className="small-icon"><Icon size={21} /></span><span><strong>{title}</strong><small>{detail}</small></span>{done ? <CheckCircle className="done-icon" size={22} /> : <ArrowRight size={19} />}</button>)}<div className="plan-tip">今天很忙？先从一张词卡开始。</div></Panel>
  <button className="studio-panel vocab-mini" onClick={() => go('vocabulary')}><span className="small-icon lavender"><Books size={24} /></span><span><span className="studio-eyebrow">WORDS INTO LIFE</span><h3>{due ? `${due} 个词，等你复习` : '让单词走进真实表达'}</h3><p>30 张场景词卡 · 翻卡自测 · 例句应用</p></span><ArrowUpRight size={24} /></button>
  <Panel className="knowledge-mini"><div><span className="studio-eyebrow">YOUR KNOWLEDGE, CONNECTED</span><h3>让读过的，成为用得上的。</h3><p>把学习笔记存入知识库，下次需要时找到它。</p><button className="text-action" onClick={() => go('library')}>打开我的知识库<ArrowRight size={16} /></button></div><button className="studio-core" onClick={() => go('ai')} aria-label="打开知识问答"><img src={`${import.meta.env.BASE_URL}k-core-unified-v10.png`} alt="玻璃 K 知识核心" /></button></Panel>
  <Panel className="recent-notes"><div className="studio-section-head"><h2>最近留下的想法</h2><button onClick={() => go('notes')}>全部笔记<ArrowUpRight size={15} /></button></div>{recent.length ? recent.map(([id, note]) => <button className="recent-note-row" key={id} onClick={() => readings.some((item) => item.id === id) ? openReading(id) : openTalk(id)}><NotePencil size={22} /><span><strong>{[...readings, ...talks].find((item) => item.id === id)?.title || '学习笔记'}</strong><small>{note.insight}</small></span><ArrowRight size={17} /></button>) : <div className="studio-empty"><NotePencil size={26} /><p>你的第一条笔记，从今天开始。</p><button className="text-action" onClick={() => openReading(reading.id)}>读完写下一个想法<ArrowRight size={16} /></button></div>}</Panel></div>
 </></Localize>;
}

function Journal({ id, title, data, updateNote, complete, saveKnowledge, type }) {const note = data.notes[id] || {};return <Localize><Panel className="learning-journal"><span className="studio-eyebrow">MAKE IT YOURS</span><h2>留下你的理解</h2><p>不用写得漂亮。写清楚它和你的关系。</p><label>{type === 'reading' ? '我的理解与一个真实例子' : '我的英文复述 / 纠错前后'}<textarea value={note.insight || ''} maxLength={12000} onChange={(e) => updateNote(id, { insight: e.target.value })} placeholder={type === 'reading' ? '这段内容让我想到……我的例子是……' : '用自己的话写 3 句英文；也可以记录原表达和更好的说法。'} /></label><label>下一步，我会这样用<textarea value={note.action || ''} maxLength={5000} onChange={(e) => updateNote(id, { action: e.target.value })} placeholder="在什么时间、什么场景，试着做一件具体的小事？" /></label><div className="journal-actions"><Button onClick={() => complete(id, title, type)}><CheckCircle size={18} />{note.completedAt ? '更新完成记录' : '完成并留下笔记'}</Button><Button secondary onClick={() => saveKnowledge(id, title)}>存入知识库<Plus size={16} /></Button></div><small>输入即保存 · {note.completedAt ? '已完成，可以继续修改与重读' : '填写两项后完成学习'}</small></Panel></Localize>;}
function ReadingPage({ id, setId, ...props }) {const item = readings.find((entry) => entry.id === id) || readings[0];const [font, setFont] = useState(18);return <Localize><><PageHeading eyebrow="THE DAILY READER" title="每日精读" description="阅读不是终点。让一个观点，在你的生活里发生。" /><div className="reading-library">{readings.map((entry) => <button key={entry.id} className={`reading-tile ${entry.color} ${entry.id === item.id ? 'selected' : ''}`} aria-pressed={entry.id === item.id} onClick={() => setId(entry.id)}><small>VOL. {entry.issue} · {entry.minutes} MIN</small><strong>{entry.title}</strong><span>{props.data.notes[entry.id]?.completedAt ? <><CheckCircle size={14} />已完成</> : entry.category}</span></button>)}</div><div className="reader-layout"><Panel className="reader-article"><div className="reader-toolbar"><span>原创成长短文 · {item.category}</span><div><button aria-label="缩小阅读字号" disabled={font <= 16} onClick={() => setFont((value) => value - 1)}>A−</button><button aria-label="放大阅读字号" disabled={font >= 24} onClick={() => setFont((value) => value + 1)}>A+</button></div></div><span className="studio-eyebrow">VOL. {item.issue} / {item.label}</span><h2>{item.title}</h2><p className="article-lead">{item.intro}</p><div className="article-body" style={{ fontSize: `${font}px` }}>{item.paragraphs.map(([title, text], index) => <section key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></section>)}</div><div className="reading-questions"><h3>合上文章，问问自己</h3>{item.questions.map((question) => <p key={question}>{question}</p>)}</div>{item.reference && <div className="reading-reference"><small>延伸阅读 · 与上方原创短文分开阅读</small><OutLink href={item.reference.url}>{item.reference.title}</OutLink><p>{item.reference.author} · 可前往 Project Gutenberg 阅读原书。</p></div>}</Panel><aside className="reader-side"><Panel><span className="studio-eyebrow">READ WITH INTENTION</span><h3>今天这样读</h3><ol className="study-steps"><li><strong>先读懂</strong><span>找出每段想解决的问题。</span></li><li><strong>再质疑</strong><span>什么情况适用？有没有反例？</span></li><li><strong>最后应用</strong><span>{item.action}</span></li></ol></Panel><Journal {...props} id={item.id} title={item.title} type="reading" /></aside></div><section className="book-shelf"><div className="studio-section-head"><h2>再往深处，读一本书。</h2><span>原书入口 · 本站编辑的阅读建议</span></div><div className="book-reference-grid">{bookReferences.map((book) => <Panel key={book.title}><span className="studio-eyebrow">{book.author}</span><h3>{book.cn}</h3><small>{book.title}</small><p>{book.guide}</p><OutLink href={book.url}>阅读原书（英文）</OutLink><button className="text-action" onClick={() => setId(book.reading)}>搭配主题精读<ArrowRight size={15} /></button></Panel>)}</div></section></></Localize>;}
function PageHeading({ eyebrow, title, description }) {return <Localize><div className="learning-heading"><span className="studio-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></Localize>;}
function EnglishPage({ id, setId, go, ...props }) {const item = talks.find((entry) => entry.id === id) || talks[0];return <Localize><><PageHeading eyebrow="ENGLISH, A LITTLE EVERY DAY" title="从听懂，到说出来。" description="真实演讲、分步跟读、自己的表达。每次专心练好一小段。" /><div className="talk-library">{talks.map((entry) => <button key={entry.id} className={`talk-tile ${entry.color} ${entry.id === item.id ? 'selected' : ''}`} aria-pressed={entry.id === item.id} onClick={() => setId(entry.id)}><span>{entry.level}<ArrowUpRight size={18} /></span><h3>{entry.cn}</h3><p>{entry.title}</p><small>{entry.speaker} · 练习 {entry.minutes} 分钟</small></button>)}</div><div className="reader-layout"><div className="learning-stack"><Panel className="speech-detail"><span className="studio-tag"><Headphones size={16} /> 本次练习 · {item.level}</span><h2>{item.title}</h2><p>{item.guide}</p><OutLink href={item.url}>打开官方{item.id === 'jobs' ? '演讲原文' : '演讲视频'}</OutLink><ol className="study-steps">{item.steps.map((step, index) => <li key={step}><strong>0{index + 1} · {['理解', '跟读与拆解', '用自己的话表达'][index]}</strong><span>{step}</span></li>)}</ol><div className="english-question"><span className="studio-eyebrow">YOUR TURN</span><h3>{item.question}</h3><p>起步句式：{item.frame}</p></div><div className="word-pills">{item.words.map((word) => <button key={word} onClick={() => go('vocabulary')}>{word}<ArrowUpRight size={13} /></button>)}</div><small className="source-note">素材来自 TED / Stanford；本站提供原创练习引导，不转载完整演讲。</small></Panel><Panel className="voice-invite"><Microphone size={28} /><div><h3>把刚学的，真正说出来。</h3><p>进入英文表达训练，复制教练提示词，让语音教练陪你纠错、重述。</p></div><Button secondary onClick={() => go('expression')}>表达训练<ArrowRight size={16} /></Button></Panel></div><aside className="reader-side"><Journal {...props} id={item.id} title={item.cn} type="english" /><Panel><h3>词汇学习参考</h3>{wordReferences.map((ref) => <div className="reference-row" key={ref.title}><OutLink href={ref.url}>{ref.title}</OutLink><small>{ref.detail}</small></div>)}<p className="source-note">词表用于延伸查阅；站内词卡是独立编写的场景练习。</p></Panel></aside></div></></Localize>;}

function Vocabulary({ data, setData, today, notify }) {
  const [group, setGroup] = useState('全部'),[mode, setMode] = useState('全部'),[selected, setSelected] = useState(null),[revealed, setRevealed] = useState(false);
  const filtered = words.filter((item) => (group === '全部' || item.group === group) && (mode !== '待复习' || !data.words[item.id] || data.words[item.id].due <= today));const item = filtered.find((word) => word.id === selected) || filtered[0];
  useEffect(() => {setRevealed(false);}, [item?.id]);
  useEffect(() => () => {window.speechSynthesis?.cancel();}, []);
  const grade = (known) => {const id = item.id;setData((current) => ({ ...current, words: { ...current.words, [id]: { known, due: dueDate(known ? 3 : 1), reviewedAt: today } } }));setRevealed(false);const index = filtered.findIndex((word) => word.id === id);setSelected(filtered[(index + 1) % filtered.length]?.id || null);notify(known ? '已记录，3 天后再复习这个词。' : '已加入明日复习，先用例句加深印象。');};
  const speak = () => {if (!window.speechSynthesis) {notify('当前浏览器不支持朗读，可使用下方词典参考。');return;}speechSynthesis.cancel();const utterance = new SpeechSynthesisUtterance(item.word);utterance.lang = 'en-US';utterance.rate = .8;utterance.onerror = () => notify('暂时无法朗读，请检查系统语音或使用词典发音。');speechSynthesis.speak(utterance);};
  return <Localize><><PageHeading eyebrow="WORDS INTO LIFE" title="不是背下来，是用起来。" description="30 张原创场景词卡。先回忆，再看释义，最后把它放进自己的句子。" /><div className="vocab-controls"><div className="studio-segments">{['全部', '成长', '表达', '工作', '日常'].map((value) => <button key={value} aria-pressed={group === value} onClick={() => {setGroup(value);setSelected(null);setRevealed(false);}}>{value}</button>)}</div><label>显示<select aria-label="词汇复习范围" value={mode} onChange={(e) => {setMode(e.target.value);setSelected(null);}}><option>全部</option><option>待复习</option></select></label></div><div className="vocab-layout"><Panel className="flashcard">{item ? <><div className="reader-toolbar"><span>{item.group} · {filtered.findIndex((word) => word.id === item.id) + 1} / {filtered.length}</span><button onClick={speak} aria-label="朗读当前单词"><SpeakerHigh size={23} /></button></div><span className="studio-eyebrow">先想一想，它是什么意思？</span><h2>{item.word}</h2>{revealed ? <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="word-answer"><h3>{item.meaning}</h3><p>{item.example}</p><span>试着把例句中的场景，换成你自己的经历。</span></motion.div> : <button className="reveal-word" onClick={() => setRevealed(true)}>显示释义与例句<ArrowRight size={17} /></button>}<div className="flashcard-actions"><Button secondary disabled={!revealed} onClick={() => grade(false)}>还需练习</Button><Button disabled={!revealed} onClick={() => grade(true)}>我记住了<Check size={18} /></Button></div><small>熟悉：3 天后复习 · 还需练习：明天再看</small></> : <div className="studio-empty"><CheckCircle size={44} /><h2>这一组，今天复习完了。</h2><p>明天再来巩固，或者切换“全部”查看其他词。</p><Button onClick={() => setMode('全部')}>查看全部词卡</Button></div>}</Panel><Panel className="word-list"><div className="studio-section-head"><h3>我的场景词库</h3><span>{words.filter((word) => data.words[word.id]?.known).length} 个熟悉</span></div>{filtered.map((word) => <button key={word.id} className={item?.id === word.id ? 'selected' : ''} onClick={() => {setSelected(word.id);setRevealed(false);}}><span>{word.word}<small>{word.group}</small></span>{data.words[word.id]?.known ? <CheckCircle size={18} /> : <ArrowRight size={16} />}</button>)}</Panel></div><div className="word-reference-bar"><span>想拓展更多词汇？</span>{wordReferences.map((ref) => <OutLink key={ref.title} href={ref.url}>{ref.title}</OutLink>)}</div></></Localize>;
}

function Notes({ data, openReading, openTalk, exportNotes, saveKnowledge }) {const entries = Object.entries(data.notes).filter(([, note]) => note.insight || note.action).sort((a, b) => (b[1].updatedAt || '').localeCompare(a[1].updatedAt || ''));return <Localize><><div className="notes-heading"><PageHeading eyebrow="YOUR THINKING, COLLECTED" title="每一次理解，都值得留下。" description="这里收集你在精读和英语练习中写下的想法。" /><Button secondary onClick={exportNotes}><DownloadSimple size={18} />导出全部笔记</Button></div><div className="notes-grid">{entries.length ? entries.map(([id, note]) => {const reading = readings.find((item) => item.id === id),item = reading || talks.find((entry) => entry.id === id);return <Panel key={id} className="saved-note"><span className="studio-tag">{reading ? '精读笔记' : '英语练习'} · {note.completedAt ? '已完成' : '草稿'}</span><h3>{item?.title || '学习笔记'}</h3><p>{note.insight || '还没有写下理解。'}</p><div className="note-next"><small>下一步行动</small>{note.action || '为这个想法补一个小行动。'}</div><div className="journal-actions"><button className="text-action" onClick={() => reading ? openReading(id) : openTalk(id)}>继续编辑<ArrowRight size={16} /></button><button className="text-action" onClick={() => saveKnowledge(id, item?.title || id)}>存入知识库<Plus size={16} /></button></div></Panel>;}) : <Panel className="studio-empty"><NotePencil size={38} /><h3>这里会成为你的想法收藏馆。</h3><p>读一篇短文，写下一个理解。第一条笔记就会出现在这里。</p><Button onClick={() => openReading(dailyReading().id)}>开始一篇精读<ArrowRight size={16} /></Button></Panel>}</div></></Localize>;}
function ProgressPage({ data, setData, today }) {const days = Array.from({ length: 7 }, (_, i) => {const date = new Date();date.setDate(date.getDate() - 6 + i);return { date: localDay(date), label: new Intl.DateTimeFormat('zh-CN', { weekday: 'short' }).format(date) };});const weekEvents = data.events.filter((item) => days.some((day) => day.date === item.date));return <Localize><><PageHeading eyebrow="SMALL STEPS, REAL PROGRESS" title="看见你走过的路。" description="用真正留下的学习记录，回看最近七天。" /><div className="progress-stats">{[['本周学习记录', weekEvents.length, '次完成'], ['写下的想法', Object.values(data.notes).filter((note) => note.insight).length, '条笔记'], ['已经熟悉的词', words.filter((word) => data.words[word.id]?.known).length, '张词卡']].map(([label, count, unit]) => <Panel key={label}><span>{label}</span><strong>{count}<small>{unit}</small></strong></Panel>)}</div><div className="reader-layout"><Panel><h2>最近七天的节奏</h2><div className="week-chart">{days.map((day) => {const count = weekEvents.filter((item) => item.date === day.date).length;return <div key={day.date}><strong>{count}</strong><span style={{ height: `${18 + Math.min(count, 6) * 18}px` }} /><small>{day.date === today ? '今天' : day.label}</small></div>;})}</div><div className="progress-events">{[...weekEvents].reverse().map((event) => <div key={event.id}><CheckCircle size={20} /><span><strong>{event.title}</strong><small>{event.date} · {event.type === 'reading' ? '精读' : event.type === 'voice' ? '表达训练' : '英语练习'}</small></span></div>)}{!weekEvents.length && <p>还没有完成记录。完成一次精读或英语练习后，这里会显示你的第一步。</p>}</div></Panel><Panel className="learning-journal"><span className="studio-eyebrow">A MOMENT TO REFLECT</span><h2>为下一周，留一个方向。</h2><p>这周什么做法值得保留？下周只改变一件事，你会选什么？</p><label>我的成长复盘<textarea value={data.weeklyReflection} onChange={(e) => setData((current) => ({ ...current, weeklyReflection: e.target.value }))} placeholder="一次具体的进步……一个要保留的做法……下周的一个小调整……" maxLength={12000} /></label><small>输入即保存，可在“学习笔记”导出备份。</small></Panel></div></></Localize>;}
function ActionPage({ actions, setActions }) {const [draft, setDraft] = useState('');return <Localize><><PageHeading eyebrow="MAKE ROOM FOR WHAT MATTERS" title="把重要的事，向前推一步。" description="任务可以很小，但要具体到你知道如何开始。" /><Panel><form className="new-action" onSubmit={(e) => {e.preventDefault();if (!draft.trim()) return;setActions((current) => [{ id: `personal-${Date.now()}`, title: draft.trim(), detail: '我的个人行动', domain: '个人成长', duration: '自主安排', completed: false }, ...current]);setDraft('');}}><input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="例如：听完一段演讲，用三句话复述" aria-label="新行动" maxLength={200} /><Button disabled={!draft.trim()} type="submit"><Plus size={18} />添加行动</Button></form><div className="personal-actions">{actions.map((action) => <button key={action.id} aria-pressed={action.completed} className={action.completed ? 'completed' : ''} onClick={() => setActions((current) => current.map((item) => item.id === action.id ? { ...item, completed: !item.completed } : item))}><span className="action-checkbox">{action.completed && <Check size={16} />}</span><span><strong>{action.title}</strong><small>{action.detail} · {action.duration}</small></span></button>)}</div></Panel></></Localize>;}
