import {useEffect,useState} from 'react';
import {methods,volumes,sourceIndex,officialIndex,recommendMethods} from './mao-content';
const fields=[['problem','我遇到的问题','例如：每天看英语视频，却仍然无法连续表达一分钟。'],['facts','事实与信息缺口','记录时间、频率、实际结果；把猜测单列。还需要问谁、查什么？'],['focus','当前关键问题','列出三个障碍，解释为什么先处理其中一个。什么证据会让你改变判断？'],['plan','最小行动与验证','明天做什么、持续多久、怎样判断有效、何时检查？'],['review','实践后的复盘','发生了什么？与预测有何不同？继续、修改还是停止？']];
export default function MaoStudy({setKnowledge}){
 const [volume,setVolume]=useState(1),[id,setId]=useState(methods[0].id),[query,setQuery]=useState(''),[message,setMessage]=useState('');
 const [initial]=useState(()=>{try{return {value:JSON.parse(localStorage.getItem('zhixu-mao-notes-v12')||'{}')}}catch{return {value:{},error:true}}});
 const [note,setNote]=useState(initial.value);
 useEffect(()=>{if(initial.error){setMessage('旧记录读取失败，原数据未覆盖。请先导出本次记录。');return;}try{localStorage.setItem('zhixu-mao-notes-v12',JSON.stringify(note))}catch{setMessage('保存失败，请导出备份。')}},[note,initial]);
 const item=methods.find(m=>m.id===id)||methods[0],vol=volumes.find(v=>v.id===volume),matched=recommendMethods(query);
 const choose=m=>{setId(m.id);setVolume(m.volume)};
 const text=()=>`# 毛选研读 · ${item.title}\n\n原创现代应用练习，非作者原话。\n参考：第 ${item.volume} 卷《${item.title}》\n目录：${sourceIndex}\n\n${fields.map(([key,label])=>`## ${label}\n${note[key]||''}`).join('\n\n')}`;
 const save=()=>{if(!note.problem?.trim()||!note.plan?.trim()){setMessage('请先填写问题和最小行动。');return;}setKnowledge(current=>[{id:crypto.randomUUID(),title:`毛选问题分析 · ${note.problem.slice(0,35)}`,type:'学习笔记',fileType:'md',space:'阅读与写作',size:'2 KB',updatedAt:new Date().toISOString(),status:'ready',tags:['毛选研读','问题分析'],summary:note.problem,content:text(),source:`第 ${item.volume} 卷《${item.title}》· 个人应用笔记`,favorite:false},...current]);setMessage('分析已保存到知识库；可在知识问答中检索。')};
 const exportNote=()=>{const url=URL.createObjectURL(new Blob([text()],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='毛选研读-问题分析.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <div className="mao-study"><header><span className="studio-eyebrow">READ · QUESTION · PRACTICE</span><h1>毛选研读与问题分析</h1><p>从具体事实出发，让阅读进入自己的生活。</p></header><div className="studio-panel mao-intro"><strong>五卷导览 · {methods.length} 篇重点方法卡 · 原创应用练习</strong><p>当前收录的是导读，不是五卷完整正文。原文、编者说明和个人应用应分别理解。第五卷按 1977 年版本辨识；你的十卷合订本与旧版扫描件需核对后使用。</p><a href={officialIndex} target="_blank" rel="noreferrer">前四卷官方阅读入口 ↗</a>　<a href={sourceIndex} target="_blank" rel="noreferrer">篇目与第五卷参考目录 ↗</a></div>
 <section className="studio-panel"><h2>我遇到了一个问题</h2><label>描述情境，寻找相关方法<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="如：英语、时间、沟通、项目、学习"/></label><p>本地关键词推荐，不是 AI 自动诊断。先选方法，再用证据填写下方分析表。</p><div className="mao-tabs">{(query?matched:methods.slice(0,3)).map(m=><button key={m.id} onClick={()=>choose(m)}>{m.method} · 第 {m.volume} 卷</button>)}</div>{query&&!matched.length&&<p>暂无明确匹配。建议从《反对本本主义》的调查清单开始。</p>}</section>
 <div className="mao-tabs" aria-label="选择卷册">{volumes.map(v=><button key={v.id} aria-pressed={volume===v.id} onClick={()=>{setVolume(v.id);setId(methods.find(m=>m.volume===v.id).id)}}>第 {v.id} 卷 · {v.title}</button>)}</div>
 <section className="studio-panel"><h2>第 {volume} 卷 · {vol.title}</h2><small>{vol.period}</small><p>{vol.guide}</p><strong>这一卷的实践产出</strong><p>{vol.output}</p></section>
 <div className="mao-reading"><aside className="studio-panel"><h3>重点篇目</h3>{methods.filter(m=>m.volume===volume).map(m=><button key={m.id} aria-pressed={id===m.id} onClick={()=>choose(m)}><strong>{m.title}</strong><small>{m.method}</small></button>)}<p>重点导读并非完整目录。更多篇目请查阅上方原文目录。</p></aside><article className="studio-panel"><span className="studio-eyebrow">第 {item.volume} 卷 · 原创导读与现代应用</span><h2>《{item.title}》</h2><h3>{item.method}</h3><p>{item.explanation}</p><h3>20 分钟精读流程</h3><ol><li>3 分钟：打开原文，确认写作时间、对象、历史问题。</li><li>8 分钟：读相关论证，分别记下观点、依据、条件；不只摘金句。</li><li>4 分钟：回答：{item.question}</li><li>5 分钟：用自己的话解释，再完成下面的实践任务。</li></ol><h3>个人成长示例（原创）</h3><p>{item.example}</p><h3>今天就做</h3><p>{item.task}</p><h3>适用边界</h3><p>{item.boundary}</p><a href={item.source} target="_blank" rel="noreferrer">打开来源目录，按篇名查阅 ↗</a></article></div>
 <section className="studio-panel"><h2>我的问题分析单</h2><p>当前参考：第 {item.volume} 卷《{item.title}》。草稿自动保存在此浏览器；可切换方法辅助同一个问题。</p>{fields.map(([key,label,hint])=><label key={key}>{label}<textarea value={note[key]||''} placeholder={hint} onChange={e=>setNote({...note,[key]:e.target.value})}/></label>)}<button className="studio-button" onClick={save}>保存分析到知识库</button> <button className="studio-button secondary" onClick={exportNote}>导出 Markdown</button>{message&&<p role="status">{message}</p>}</section><section className="studio-panel"><h2>你的参考书库 · 初步核验</h2><p>13 份 PDF 已只读抽查，尚未完成全文入库。扫描书需要 OCR 和校对；文字层也可能存在识别错误。文件不会随网站公开发布。</p><ul><li>《毛泽东选集》合订本：4,638 页，封面标“十卷合订本”，有文字层；需核对篇目和版本。</li><li>《毛泽东文集》1–8 卷：1,801 页；年谱全九卷：2,756 页。用于补充原文与历史背景，不能混标为《选集》。</li><li>1967 年版第一卷：321 页，有文字层且存在识别错误。第二至四卷、1952 年标名两卷及农村调查文集：抽查无文字层，待 OCR。</li><li>诗词讲解、古典小说读评：辅助文学与表达学习；第三方解读要与原作者文字分开。</li></ul><p>使用现有“导入知识”可导入已校对的 TXT / Markdown；PDF 正文解析与页码检索尚待接入，不能将上传成功视为全文已可检索。</p></section></div>
}
