import {useEffect,useRef,useState} from 'react';
import {getDocument,GlobalWorkerOptions} from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
GlobalWorkerOptions.workerSrc=workerUrl;
export default function PdfReader({url,page,onPage,en}){
 const [doc,setDoc]=useState(null),[error,setError]=useState(''),[text,setText]=useState('');const canvas=useRef(null),container=useRef(null);
 useEffect(()=>{let active=true;setDoc(null);setError('');const base=import.meta.env.BASE_URL;const task=getDocument({url,isEvalSupported:false,cMapUrl:base+'cmaps/',cMapPacked:true,standardFontDataUrl:base+'standard_fonts/',wasmUrl:base+'wasm/'});task.promise.then(pdf=>{if(active)setDoc(pdf);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;task.destroy();};},[url]);
 useEffect(()=>{if(!doc)return;let active=true,render;setText('');const p=Math.min(Math.max(page,1),doc.numPages);if(p!==page){onPage(p);return;}doc.getPage(p).then(async pdf=>{if(!active)return;const viewport=pdf.getViewport({scale:1});const scale=Math.min(2,window.devicePixelRatio||1)*Math.max(280,container.current.clientWidth-20)/viewport.width;const scaled=pdf.getViewport({scale});const c=canvas.current;c.width=scaled.width;c.height=scaled.height;render=pdf.render({canvasContext:c.getContext('2d'),viewport:scaled});await render.promise;const content=await pdf.getTextContent();if(active)setText(content.items.map(x=>x.str||'').join(' '));}).catch(e=>{if(active&&e.name!=='RenderingCancelledException')setError(e.message);});return()=>{active=false;render?.cancel();};},[doc,page]);
 return <div className="pdf-renderer" ref={container}><div className="pdf-pagination"><button disabled={!doc||page<=1} onClick={()=>onPage(page-1)}>{en?'Previous':'上一页'}</button><span>{page} / {doc?.numPages||'…'}</span><button disabled={!doc||page>=doc.numPages} onClick={()=>onPage(page+1)}>{en?'Next':'下一页'}</button></div>{error&&<p role="alert">{error}</p>}<canvas ref={canvas} aria-label={en?`PDF page ${page}`:`原书第 ${page} 页`}/>{doc&&<details><summary>{en?'Page text / accessible reading':'本页文字 / 辅助阅读'}</summary><p>{text||(en?'Scanned page or no text layer. Read the original image above.':'本页为扫描图或无文字层，请阅读上方原页。')}</p></details>}</div>;
}
