import {useEffect,useRef,useState} from 'react';
import {getDocument,GlobalWorkerOptions} from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
GlobalWorkerOptions.workerSrc=workerUrl;
export default function PdfReader({url,page,onPage,en}){
 const [doc,setDoc]=useState(null),[error,setError]=useState(''),[text,setText]=useState(''),[width,setWidth]=useState(0),[zoom,setZoom]=useState(1),[theme,setTheme]=useState('paper');const canvas=useRef(null),container=useRef(null);
 useEffect(()=>{const observer=new ResizeObserver(([entry])=>setWidth(entry.contentRect.width));observer.observe(container.current);return()=>observer.disconnect();},[]);
 useEffect(()=>{let active=true;setDoc(null);setError('');const base=import.meta.env.BASE_URL;const task=getDocument({url,isEvalSupported:false,cMapUrl:base+'cmaps/',cMapPacked:true,standardFontDataUrl:base+'standard_fonts/',wasmUrl:base+'wasm/'});task.promise.then(pdf=>{if(active)setDoc(pdf);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;task.destroy();};},[url]);
 useEffect(()=>{if(!doc||!width)return;let active=true,render;setText('');setError('');const p=Math.min(Math.max(page,1),doc.numPages);if(p!==page){onPage(p);return;}doc.getPage(p).then(async pdf=>{if(!active)return;const viewport=pdf.getViewport({scale:1});const cssWidth=Math.max(180,width-24)*zoom;const scale=Math.min(2,window.devicePixelRatio||1)*cssWidth/viewport.width;const scaled=pdf.getViewport({scale});const c=canvas.current;c.width=scaled.width;c.height=scaled.height;c.style.width=cssWidth+'px';render=pdf.render({canvasContext:c.getContext('2d'),viewport:scaled});await render.promise;const content=await pdf.getTextContent();if(active)setText(content.items.map(x=>x.str||'').join(' '));}).catch(e=>{if(active&&e.name!=='RenderingCancelledException')setError(e.message);});return()=>{active=false;render?.cancel();};},[doc,page,width,zoom]);
 const turn=p=>{if(doc){onPage(Math.min(doc.numPages,Math.max(1,p)));container.current.scrollTop=0;}};
 return <div className={`pdf-renderer paper-${theme}`} ref={container}><div className="reading-settings"><label>{en?'Paper':'纸张'} <select value={theme} onChange={e=>setTheme(e.target.value)}><option value="paper">{en?'Warm':'暖纸'}</option><option value="white">{en?'White':'白纸'}</option><option value="night">{en?'Night':'夜读'}</option></select></label><label>{en?'Zoom':'缩放'} <select value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value="1">100%</option><option value="1.25">125%</option><option value="1.5">150%</option><option value="2">200%</option></select></label></div><div className="pdf-pagination"><button disabled={!doc||page<=1} onClick={()=>turn(page-1)}>{en?'Previous':'上一页'}</button><label><input aria-label={en?'Page number':'跳转页码'} type="number" min="1" max={doc?.numPages||1} value={page} disabled={!doc} onChange={e=>turn(Number(e.target.value)||1)}/> / {doc?.numPages||'…'}</label><button disabled={!doc||page>=doc.numPages} onClick={()=>turn(page+1)}>{en?'Next':'下一页'}</button></div>{!doc&&!error&&<p role="status">{en?'Preparing pages…':'正在准备书页…'}</p>}{error&&<p role="alert">{error}</p>}<canvas ref={canvas} aria-label={en?`PDF page ${page}`:`原书第 ${page} 页`}/>{doc&&<details><summary>{en?'Page text / accessible reading':'本页文字 / 辅助阅读'}</summary><p>{text||(en?'Scanned page or no text layer. Use zoom to read the original.':'本页为扫描图或无文字层，可缩放阅读原页，无法自动重排字体。')}</p></details>}</div>;
}
