import {lazy,Suspense,useRef,useState} from 'react';
const Reader=lazy(()=>import('./AnnotatedPdfReader'));
export default function ReadingWorkspace({url,note,edit,en,journal,setJournal,status}){
 const [removed,setRemoved]=useState(null),[filter,setFilter]=useState(false);const latest=useRef(note);latest.current=note;
 const annotations=note.annotations||[];
 const add=value=>{if(annotations.length>=2000)return;const entry={...value,id:crypto.randomUUID(),thought:'',createdAt:new Date().toISOString()};edit({annotations:[...latest.current.annotations||[],entry]});if(value.type==='thought')setJournal(true);};
 const update=(id,thought)=>edit({annotations:latest.current.annotations.map(a=>a.id===id?{...a,thought}:a)});
 return <div className={`reading-workspace ${journal?'show-journal':'show-pages'}`}><section className="workspace-pages"><Suspense fallback={<p role="status">{en?'Preparing reader…':'准备阅读器…'}</p>}><Reader url={url} page={note.page} onPage={page=>edit({page})} en={en} annotations={annotations} onAdd={add}/></Suspense></section><aside className="encrypted-journal"><h3>{en?'My reading notebook':'我的阅读手记'}</h3><p>{en?'Find a claim, question its evidence, try one action.':'读懂一个观点，追问它的证据，留下一个可验证的行动。'}</p><label>{en?'Overall notes':'整本书笔记'}<textarea value={note.notes} onChange={e=>edit({notes:e.target.value})} maxLength={30000} placeholder={en?'What changed my thinking?':'今天哪一句话改变了我的理解？'}/></label><header className="annotation-list-heading"><h3>{en?'Marks & thoughts':'划线与想法'} · {annotations.length}</h3><label><input type="checkbox" checked={filter} onChange={e=>setFilter(e.target.checked)}/>{en?'This page':'仅本页'}</label></header><button className="add-page-thought" disabled={annotations.length>=2000} onClick={()=>add({page:note.page,type:'thought'})}>{en?'Add page thought':'添加本页想法'}</button>{annotations.length>=2000&&<p>{en?'2,000 annotations reached. Export a backup.':'已达 2000 条标注，请导出备份。'}</p>}{removed&&<button onClick={()=>{edit({annotations:[...annotations,removed]});setRemoved(null);}}>{en?'Undo deletion':'撤销删除'}</button>}
  {annotations.filter(a=>!filter||a.page===note.page).map(a=><article className="annotation-card" key={a.id}><div><button onClick={()=>{edit({page:a.page});setJournal(false);}}>{en?'Page':'第'} {a.page} {en?'':'页'} · {a.type==='highlight'?(en?'Highlight':'高亮'):a.type==='underline'?(en?'Underline':'划线'):(en?'Thought':'想法')}</button><button aria-label={en?'Remove annotation':'删除标注'} onClick={()=>{setRemoved(a);edit({annotations:annotations.filter(x=>x.id!==a.id)});}}>×</button></div>{a.quote&&<blockquote>{a.quote}</blockquote>}<label>{en?'My thought':'我的想法'}<textarea value={a.thought||''} maxLength={4000} onChange={e=>update(a.id,e.target.value)} placeholder={en?'Why does this matter?':'为什么重要？与我的经历有什么联系？'}/></label></article>)}
  {!annotations.length&&<p>{en?'Choose Highlight or Underline, then drag on a page. You can also add a page thought here.':'选择高亮或划线后，在原页拖动框选；也可以直接添加本页想法。'}</p>}<small>{en?'Saved locally, unencrypted; not synced. Export regularly.':'自动保存到本浏览器，未加密、不自动同步，请定期导出备份。'}</small>{status&&<p role="status">{status}</p>}
 </aside></div>;
}
